export default function getPrompt() {
	const prompts = [
		"City on stilts",
		"Rainbow road",
		"Garden in space",
		"Enchanted tea party",
		"Monster amusement park",
		"Haunted mansion carousel",
		"Butterfly factory",
		"Robot rodeo",
		"Underwater castle",
		"Circus on the moon",
		"Mushroom village",
		"Magic garden",
		"Space zoo",
		"Dinosaur park",
		"Steampunk airship",
		"Chocolate factory",
		"Cloud surfing",
		"Dragon festival",
		"Clockwork city",
		"Mermaid tavern",
		"Cloud cityscape",
		"Ocean of flowers",
		"Cosmic ice cream",
		"Treehouse dreams",
		"Floating island",
		"Jungle disco",
		"Galactic pizza",
		"Space garden",
		"Mystical carousel",
		"Enchanted forest",
		"Alien tea party",
		"Rainbow labyrinth",
		"Robot orchestra",
		"Underwater circus",
		"Flying bookstore",
		"Time-traveling train",
		"Magic mirror",
		"Steampunk dragon",
		"Moon base",
		"Mermaid parade",
		"Castle in the clouds",
		"Crystal cave",
		"Jungle arcade",
		"Beach sunset",
		"Winter wonderland",
		"Underwater world",
		"City skyline",
		"Jungle adventure",
		"Outer space",
		"Mountain peak",
		"Autumn leaves",
		"Summer garden",
		"Desert oasis",
		"Star-filled sky",
		"Forest trail",
		"Tropical paradise",
		"Moonlit lake",
		"Ocean waves",
		"Rainy day",
		"Sunny day",
		"Campfire scene",
		"Arctic landscape",
		"Butterfly wings",
		"Sunflower field",
		"Birds in flight",
		"Dragonfly wings",
		"Flower garden",
		"Vintage car",
		"Woodland creatures",
		"Barnyard animals",
		"Halloween night",
		"Fairy tale castle",
		"Haunted house",
		"Pumpkin patch",
		"Surreal landscape",
		"Space station",
		"Galaxy far, far away",
		"Robot invasion",
		"Fantasy forest",
		"Dragon's lair",
		"Magic potion",
		"Alien planet",
		"Undersea creatures",
		"Rainbow bridge",
		"Superhero showdown",
		"Garden tea party",
		"Mad scientist lab",
		"Time machine",
		"Steampunk city",
		"Pirate adventure",
		"Mermaid lagoon",
		"Enchanted garden",
		"Ice cream truck",
		"Fireworks display",
		"Safari adventure",
		"Monster mash",
		"Circus extravaganza",
		"Mythical creatures",
		"Oceanic wonderland"
	];
	return prompts[Math.floor(Math.random() * prompts.length)];
}
