export default function getPrompt() {
	const prompts = [
		"City on stilts",
		"Rainbow road",
		"Garden in space",
		"Enchanted tea party",
		"Monster amusement park",
		"Haunted mansion carousel",
		"Butterfly factory",
		"Robot rodeo",
		"Underwater castle",
		"Circus on the moon",
		"Mushroom village",
		"Magic garden",
		"Space zoo",
		"Dinosaur park",
		"Steampunk airship",
		"Chocolate factory",
		"Cloud surfing",
		"Dragon festival",
		"Clockwork city",
		"Mermaid tavern",
		"Cloud cityscape",
		"Ocean of flowers",
		"Cosmic ice cream",
		"Treehouse dreams",
		"Floating island",
		"Jungle disco",
		"Galactic pizza",
		"Space garden",
		"Mystical carousel",
		"Enchanted forest",
		"Alien tea party",
		"Rainbow labyrinth",
		"Robot orchestra",
		"Underwater circus",
		"Flying bookstore",
		"Time-traveling train",
		"Magic mirror",
		"Steampunk dragon",
		"Moon base",
		"Mermaid parade",
		"Castle in the clouds",
		"Crystal cave",
		"Jungle arcade"
	];
	return prompts[Math.floor(Math.random() * prompts.length)];
}
